version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            npm i
            npm run dist-all
      - run:
          name: "Publish to Store"
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get -yq install snapcraft
            mkdir .snapcraft
            echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
            snapcraft push dist/*.snap --release stable
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/